# SPDX-License-Identifier: GPL-2.0

subdir-ccflags-y += \
		-I$(ROOT_DIR)/private/google-modules/bms \

include $(srctree)/google-modules/soc/gs/Makefile.include

obj-$(CONFIG_PIXEL_POWER_REBOOT) += pixel-reboot.o
